name: Bluetags
version: '${project.version}'
main: com.bluefalconhd.bluetags.Bluetags
api-version: '1.20'
commands:
  bluetags:
    description: Manage player tags.
    usage: /bluetags <player> [add|remove|toggle|list] <tag> | /bluetags [reload|info]
    permission: myplugin.bluetags
    permission-message: You do not have permission to use this command.